@startuml

' ComputeKernel is a protocol which requires a class implement an encode() method
' This encode method is passed a command encoder and a pipeline state which allows the implementing class to populate the buffer arguments for a kernel and setup how many threads need to be dispatched
' ComputeKernel also requires the implementing class make the kernel function name it will use known
' ComputeKernel exists to handle configuration of kernels, given each class will have it's own logic on how it wants to call kernels

' Note that allocating device memory is NOT handled by Computekernels rather, buffers will be passed to them by their corresponding factory classes (then the ComputeKernels can figure out where it goes in the function call)

interface ComputeKernel <<protocol>> {
    + {static} {abstract} getFunctionName() : String
    + {abstract} encode() : ((MTLComputeCommandEncoder,MTLComputePipelineState) throws -> Void)
}

note top of ComputeKernel
    Defines a class which knows how to encode a kernel shader given buffers and dispatch threads
    Has a corresponding factory class (ComputeKernelCreatable) which instanciates the class
end note

interface ComputeKernelCreatable <<protocol>> {
    + {static} {abstract} getFactoryName() : String
    + {abstract} createKernel(bufable: MTBufable, context: MetalComputeContext) : ComputeKernel <<async>> <<throws>>
}

note bottom of ComputeKernelCreatable
    Defines a factory class for a corresponding ComputeKernel,
    Responsible for allocating buffer memory on device based on parameters given
end note

interface MTBufable <<protocol>> {
    + {abstract} toMTLBuffer(_ device: MTLDevice) : MTLBuffer <<async>> <<throws>>
    + {abstract} MTLBufferSize() : UInt32 <<throws>>
}

class MetalComputeContext <<actor>> {
 - pipelineCache : [String:Task<MTLComputePipelineState,Error>]
 - kernelRegistry : [String:ComputeKernelCreatable]
 + getPipelineState(for computeObject: ComputeKernel) : MTLComputePipelineState <<async>> <<throws>>
 + getQueue() : MTLCommandQueue <<nonisolated>>
 + getDevice() : MTLDevice <<nonisolated>>
 + getKernel(typ : ComputeKernelCreateable, buf : MTBufable) : ComputeKernel <<async>> <<throws>>
}

class MetalRunner <<actor>> {
        + {static} runCompute(from context : MetalComputeContext, for kernels : [ComputeKernel], callback cb : @escaping @Sendable (MTLCommandBuffer) -> ()) <<async>> <<throws>>
}

class ImageData <<Identifiable, MTBufable>> {
    - pixelData : UnsafeMutablePointer<UInt8>
    + init(_ img : CGImage) : ImageData
}

class GrayScaleConvert <<ComputeKernel, Sendable>> {
    - rgbaBuf : MTLBuffer
    - grayScaleBuf : MTLBuffer
}

class GrayScaleKernelFactory <<ComputeKernelCreatable, Sendable>> {
}

ComputeKernelCreatable .l.> ComputeKernel
ComputeKernelCreatable .r.> MTBufable
ComputeKernelCreatable .u.> MetalComputeContext
GrayScaleConvert .u.|> ComputeKernel
GrayScaleKernelFactory .u.|> ComputeKernelCreatable
ImageData .u.|> MTBufable
MetalRunner .l.> MetalComputeContext

@enduml
